name: 'CD-IntelDS-ddh-qa-v1'

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
   - cron: '05 14 * * *' # Triggers every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Display Hello World
      run: echo "Hello, World!"
